# TEST FILE - Apache httpd mod_ssl
<VirtualHost *:443>
  ServerName legacy.ci.test
  SSLEngine on
  SSLCertificateFile      /etc/pki/ci/sha1-signed.crt
  SSLCertificateKeyFile   /etc/pki/ci/sha1-signed.key
  SSLCertificateChainFile /etc/pki/ci/intermediate-ca.crt
  SSLProtocol all -SSLv3
  SSLCipherSuite HIGH:MEDIUM:!aNULL:3DES
  SSLHonorCipherOrder off
</VirtualHost>
